# Generated by Django 5.2.9 on 2026-09-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inbox_seen_at',
            field=models.DateTimeField(blank=True, help_text='Terakhir kali buka inbox.', null=True),
        ),
    ]
