# Generated by Django 5.2.9 on 2026-09-21 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matkul', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('jadwal', 'Jadwal Kuliah'), ('tugas', 'Tugas Kuliah'), ('event', 'Event')], default='tugas', max_length=20)),
                ('deadline', models.DateTimeField(help_text='Tanggal + jam deadline / pelaksanaan.')),
                ('lokasi', models.CharField(blank=True, default='', help_text='Ruang / lokasi event.', max_length=200)),
                ('link', models.URLField(blank=True, default='', help_text='Link webinar / bootcamp / pengumpulan.')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('matkul', models.ForeignKey(blank=True, help_text='Kosongkan kalau event umum, bukan matkul tertentu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='matkul.matakuliah')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField(max_length=1000)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentars', to='announcements.announcement')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='TandaiSelesai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selesai_pada', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yang_selesai', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_selesai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-selesai_pada'],
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
