# Generated by Django 5.2.9 on 2026-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: TI101', max_length=20, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('dosen', models.CharField(help_text='Nama dosen pengampu', max_length=120)),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('ruang', models.CharField(blank=True, default='', max_length=50)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hari', 'jam_mulai', 'kode'],
            },
        ),
    ]
