# Generated by Django 5.2.9 on 2026-09-21 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='no_wa_dosen',
            field=models.CharField(blank=True, default='', help_text='Contoh: 081234567890 (opsional, jadi tombol WA)', max_length=20),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='sks',
            field=models.PositiveSmallIntegerField(default=2, help_text='1-6', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
